// Code generated by MockGen. DO NOT EDIT.
// Source: storage/s3.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStorageService is a mock of StorageService interface.
type MockStorageService struct {
	ctrl     *gomock.Controller
	recorder *MockStorageServiceMockRecorder
}

// MockStorageServiceMockRecorder is the mock recorder for MockStorageService.
type MockStorageServiceMockRecorder struct {
	mock *MockStorageService
}

// NewMockStorageService creates a new mock instance.
func NewMockStorageService(ctrl *gomock.Controller) *MockStorageService {
	mock := &MockStorageService{ctrl: ctrl}
	mock.recorder = &MockStorageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageService) EXPECT() *MockStorageServiceMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockStorageService) DeleteFile(ctx context.Context, fileURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, fileURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockStorageServiceMockRecorder) DeleteFile(ctx, fileURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockStorageService)(nil).DeleteFile), ctx, fileURL)
}

// GetPublicURL mocks base method.
func (m *MockStorageService) GetPublicURL(key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicURL", key)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPublicURL indicates an expected call of GetPublicURL.
func (mr *MockStorageServiceMockRecorder) GetPublicURL(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicURL", reflect.TypeOf((*MockStorageService)(nil).GetPublicURL), key)
}

// UploadFile mocks base method.
func (m *MockStorageService) UploadFile(ctx context.Context, file multipart.File, header *multipart.FileHeader, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, file, header, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockStorageServiceMockRecorder) UploadFile(ctx, file, header, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockStorageService)(nil).UploadFile), ctx, file, header, path)
}
