// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/seat_lock_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockSeatLockService is a mock of SeatLockService interface.
type MockSeatLockService struct {
	ctrl     *gomock.Controller
	recorder *MockSeatLockServiceMockRecorder
}

// MockSeatLockServiceMockRecorder is the mock recorder for MockSeatLockService.
type MockSeatLockServiceMockRecorder struct {
	mock *MockSeatLockService
}

// NewMockSeatLockService creates a new mock instance.
func NewMockSeatLockService(ctrl *gomock.Controller) *MockSeatLockService {
	mock := &MockSeatLockService{ctrl: ctrl}
	mock.recorder = &MockSeatLockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeatLockService) EXPECT() *MockSeatLockServiceMockRecorder {
	return m.recorder
}

// CleanExpiredLocks mocks base method.
func (m *MockSeatLockService) CleanExpiredLocks(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanExpiredLocks", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanExpiredLocks indicates an expected call of CleanExpiredLocks.
func (mr *MockSeatLockServiceMockRecorder) CleanExpiredLocks(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanExpiredLocks", reflect.TypeOf((*MockSeatLockService)(nil).CleanExpiredLocks), ctx)
}

// GetLockedSeats mocks base method.
func (m *MockSeatLockService) GetLockedSeats(ctx context.Context, tripID uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLockedSeats", ctx, tripID)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLockedSeats indicates an expected call of GetLockedSeats.
func (mr *MockSeatLockServiceMockRecorder) GetLockedSeats(ctx, tripID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLockedSeats", reflect.TypeOf((*MockSeatLockService)(nil).GetLockedSeats), ctx, tripID)
}

// LockSeats mocks base method.
func (m *MockSeatLockService) LockSeats(ctx context.Context, tripID uuid.UUID, seatIDs []uuid.UUID, sessionID string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockSeats", ctx, tripID, seatIDs, sessionID)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockSeats indicates an expected call of LockSeats.
func (mr *MockSeatLockServiceMockRecorder) LockSeats(ctx, tripID, seatIDs, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockSeats", reflect.TypeOf((*MockSeatLockService)(nil).LockSeats), ctx, tripID, seatIDs, sessionID)
}

// UnlockSeats mocks base method.
func (m *MockSeatLockService) UnlockSeats(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockSeats", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockSeats indicates an expected call of UnlockSeats.
func (mr *MockSeatLockServiceMockRecorder) UnlockSeats(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockSeats", reflect.TypeOf((*MockSeatLockService)(nil).UnlockSeats), ctx, sessionID)
}

// ValidateSeatAvailability mocks base method.
func (m *MockSeatLockService) ValidateSeatAvailability(ctx context.Context, tripID uuid.UUID, seatIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSeatAvailability", ctx, tripID, seatIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateSeatAvailability indicates an expected call of ValidateSeatAvailability.
func (mr *MockSeatLockServiceMockRecorder) ValidateSeatAvailability(ctx, tripID, seatIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSeatAvailability", reflect.TypeOf((*MockSeatLockService)(nil).ValidateSeatAvailability), ctx, tripID, seatIDs)
}
