// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/token_manager.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTokenManager is a mock of TokenManager interface.
type MockTokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockTokenManagerMockRecorder
}

// MockTokenManagerMockRecorder is the mock recorder for MockTokenManager.
type MockTokenManagerMockRecorder struct {
	mock *MockTokenManager
}

// NewMockTokenManager creates a new mock instance.
func NewMockTokenManager(ctrl *gomock.Controller) *MockTokenManager {
	mock := &MockTokenManager{ctrl: ctrl}
	mock.recorder = &MockTokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenManager) EXPECT() *MockTokenManagerMockRecorder {
	return m.recorder
}

// Blacklist mocks base method.
func (m *MockTokenManager) Blacklist(ctx context.Context, token string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Blacklist", ctx, token)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Blacklist indicates an expected call of Blacklist.
func (mr *MockTokenManagerMockRecorder) Blacklist(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blacklist", reflect.TypeOf((*MockTokenManager)(nil).Blacklist), ctx, token)
}

// BlacklistUserTokens mocks base method.
func (m *MockTokenManager) BlacklistUserTokens(ctx context.Context, userID uuid.UUID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlacklistUserTokens", ctx, userID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// BlacklistUserTokens indicates an expected call of BlacklistUserTokens.
func (mr *MockTokenManagerMockRecorder) BlacklistUserTokens(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlacklistUserTokens", reflect.TypeOf((*MockTokenManager)(nil).BlacklistUserTokens), ctx, userID)
}

// IsBlacklisted mocks base method.
func (m *MockTokenManager) IsBlacklisted(ctx context.Context, token string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBlacklisted", ctx, token)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBlacklisted indicates an expected call of IsBlacklisted.
func (mr *MockTokenManagerMockRecorder) IsBlacklisted(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBlacklisted", reflect.TypeOf((*MockTokenManager)(nil).IsBlacklisted), ctx, token)
}

// IsUserTokensBlacklisted mocks base method.
func (m *MockTokenManager) IsUserTokensBlacklisted(ctx context.Context, userID uuid.UUID, tokenIssuedAt int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserTokensBlacklisted", ctx, userID, tokenIssuedAt)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUserTokensBlacklisted indicates an expected call of IsUserTokensBlacklisted.
func (mr *MockTokenManagerMockRecorder) IsUserTokensBlacklisted(ctx, userID, tokenIssuedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserTokensBlacklisted", reflect.TypeOf((*MockTokenManager)(nil).IsUserTokensBlacklisted), ctx, userID, tokenIssuedAt)
}
