// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/external_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "bus-booking/chatbot-service/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTripServiceClient is a mock of TripServiceClient interface.
type MockTripServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockTripServiceClientMockRecorder
}

// MockTripServiceClientMockRecorder is the mock recorder for MockTripServiceClient.
type MockTripServiceClientMockRecorder struct {
	mock *MockTripServiceClient
}

// NewMockTripServiceClient creates a new mock instance.
func NewMockTripServiceClient(ctrl *gomock.Controller) *MockTripServiceClient {
	mock := &MockTripServiceClient{ctrl: ctrl}
	mock.recorder = &MockTripServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTripServiceClient) EXPECT() *MockTripServiceClientMockRecorder {
	return m.recorder
}

// GetTripByID mocks base method.
func (m *MockTripServiceClient) GetTripByID(ctx context.Context, tripID string) (*model.TripDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripByID", ctx, tripID)
	ret0, _ := ret[0].(*model.TripDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripByID indicates an expected call of GetTripByID.
func (mr *MockTripServiceClientMockRecorder) GetTripByID(ctx, tripID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripByID", reflect.TypeOf((*MockTripServiceClient)(nil).GetTripByID), ctx, tripID)
}

// SearchTrips mocks base method.
func (m *MockTripServiceClient) SearchTrips(ctx context.Context, params *model.TripSearchParams) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTrips", ctx, params)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTrips indicates an expected call of SearchTrips.
func (mr *MockTripServiceClientMockRecorder) SearchTrips(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTrips", reflect.TypeOf((*MockTripServiceClient)(nil).SearchTrips), ctx, params)
}

// MockBookingServiceClient is a mock of BookingServiceClient interface.
type MockBookingServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockBookingServiceClientMockRecorder
}

// MockBookingServiceClientMockRecorder is the mock recorder for MockBookingServiceClient.
type MockBookingServiceClientMockRecorder struct {
	mock *MockBookingServiceClient
}

// NewMockBookingServiceClient creates a new mock instance.
func NewMockBookingServiceClient(ctrl *gomock.Controller) *MockBookingServiceClient {
	mock := &MockBookingServiceClient{ctrl: ctrl}
	mock.recorder = &MockBookingServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingServiceClient) EXPECT() *MockBookingServiceClientMockRecorder {
	return m.recorder
}

// CreateGuestBooking mocks base method.
func (m *MockBookingServiceClient) CreateGuestBooking(ctx context.Context, req *model.CreateGuestBookingRequest) (*model.BookingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGuestBooking", ctx, req)
	ret0, _ := ret[0].(*model.BookingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGuestBooking indicates an expected call of CreateGuestBooking.
func (mr *MockBookingServiceClientMockRecorder) CreateGuestBooking(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGuestBooking", reflect.TypeOf((*MockBookingServiceClient)(nil).CreateGuestBooking), ctx, req)
}

// GetBookingByID mocks base method.
func (m *MockBookingServiceClient) GetBookingByID(ctx context.Context, bookingID string) (*model.BookingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingByID", ctx, bookingID)
	ret0, _ := ret[0].(*model.BookingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingByID indicates an expected call of GetBookingByID.
func (mr *MockBookingServiceClientMockRecorder) GetBookingByID(ctx, bookingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingByID", reflect.TypeOf((*MockBookingServiceClient)(nil).GetBookingByID), ctx, bookingID)
}

// GetBookingByReference mocks base method.
func (m *MockBookingServiceClient) GetBookingByReference(ctx context.Context, reference, email string) (*model.BookingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingByReference", ctx, reference, email)
	ret0, _ := ret[0].(*model.BookingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingByReference indicates an expected call of GetBookingByReference.
func (mr *MockBookingServiceClientMockRecorder) GetBookingByReference(ctx, reference, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingByReference", reflect.TypeOf((*MockBookingServiceClient)(nil).GetBookingByReference), ctx, reference, email)
}

// MockPaymentServiceClient is a mock of PaymentServiceClient interface.
type MockPaymentServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentServiceClientMockRecorder
}

// MockPaymentServiceClientMockRecorder is the mock recorder for MockPaymentServiceClient.
type MockPaymentServiceClientMockRecorder struct {
	mock *MockPaymentServiceClient
}

// NewMockPaymentServiceClient creates a new mock instance.
func NewMockPaymentServiceClient(ctrl *gomock.Controller) *MockPaymentServiceClient {
	mock := &MockPaymentServiceClient{ctrl: ctrl}
	mock.recorder = &MockPaymentServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentServiceClient) EXPECT() *MockPaymentServiceClientMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockPaymentServiceClient) CreateTransaction(ctx context.Context, req *model.CreateTransactionRequest) (*model.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, req)
	ret0, _ := ret[0].(*model.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockPaymentServiceClientMockRecorder) CreateTransaction(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockPaymentServiceClient)(nil).CreateTransaction), ctx, req)
}
