// Code generated by MockGen. DO NOT EDIT.
// Source: queue/delayed_queue.go

// Package mocks is a generated GoMock package.
package mocks

import (
	queue "bus-booking/shared/queue"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockDelayedQueueManager is a mock of DelayedQueueManager interface.
type MockDelayedQueueManager struct {
	ctrl     *gomock.Controller
	recorder *MockDelayedQueueManagerMockRecorder
}

// MockDelayedQueueManagerMockRecorder is the mock recorder for MockDelayedQueueManager.
type MockDelayedQueueManagerMockRecorder struct {
	mock *MockDelayedQueueManager
}

// NewMockDelayedQueueManager creates a new mock instance.
func NewMockDelayedQueueManager(ctrl *gomock.Controller) *MockDelayedQueueManager {
	mock := &MockDelayedQueueManager{ctrl: ctrl}
	mock.recorder = &MockDelayedQueueManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDelayedQueueManager) EXPECT() *MockDelayedQueueManagerMockRecorder {
	return m.recorder
}

// Poll mocks base method.
func (m *MockDelayedQueueManager) Poll(ctx context.Context, queueName string, limit int) ([]*queue.DelayedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Poll", ctx, queueName, limit)
	ret0, _ := ret[0].([]*queue.DelayedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Poll indicates an expected call of Poll.
func (mr *MockDelayedQueueManagerMockRecorder) Poll(ctx, queueName, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Poll", reflect.TypeOf((*MockDelayedQueueManager)(nil).Poll), ctx, queueName, limit)
}

// Schedule mocks base method.
func (m *MockDelayedQueueManager) Schedule(ctx context.Context, queueName string, item *queue.DelayedItem, executeAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Schedule", ctx, queueName, item, executeAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Schedule indicates an expected call of Schedule.
func (mr *MockDelayedQueueManagerMockRecorder) Schedule(ctx, queueName, item, executeAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schedule", reflect.TypeOf((*MockDelayedQueueManager)(nil).Schedule), ctx, queueName, item, executeAt)
}
