// Code generated by MockGen. DO NOT EDIT.
// Source: queue/redis_queue.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockQueueManager is a mock of QueueManager interface.
type MockQueueManager struct {
	ctrl     *gomock.Controller
	recorder *MockQueueManagerMockRecorder
}

// MockQueueManagerMockRecorder is the mock recorder for MockQueueManager.
type MockQueueManagerMockRecorder struct {
	mock *MockQueueManager
}

// NewMockQueueManager creates a new mock instance.
func NewMockQueueManager(ctrl *gomock.Controller) *MockQueueManager {
	mock := &MockQueueManager{ctrl: ctrl}
	mock.recorder = &MockQueueManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueManager) EXPECT() *MockQueueManagerMockRecorder {
	return m.recorder
}

// Length mocks base method.
func (m *MockQueueManager) Length(ctx context.Context, queueName string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Length", ctx, queueName)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Length indicates an expected call of Length.
func (mr *MockQueueManagerMockRecorder) Length(ctx, queueName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Length", reflect.TypeOf((*MockQueueManager)(nil).Length), ctx, queueName)
}

// Pop mocks base method.
func (m *MockQueueManager) Pop(ctx context.Context, queueName string, timeout time.Duration, target interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pop", ctx, queueName, timeout, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pop indicates an expected call of Pop.
func (mr *MockQueueManagerMockRecorder) Pop(ctx, queueName, timeout, target interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pop", reflect.TypeOf((*MockQueueManager)(nil).Pop), ctx, queueName, timeout, target)
}

// Push mocks base method.
func (m *MockQueueManager) Push(ctx context.Context, queueName string, item interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", ctx, queueName, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockQueueManagerMockRecorder) Push(ctx, queueName, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockQueueManager)(nil).Push), ctx, queueName, item)
}
