// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/bank_account_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "bus-booking/payment-service/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockBankAccountRepository is a mock of BankAccountRepository interface.
type MockBankAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBankAccountRepositoryMockRecorder
}

// MockBankAccountRepositoryMockRecorder is the mock recorder for MockBankAccountRepository.
type MockBankAccountRepositoryMockRecorder struct {
	mock *MockBankAccountRepository
}

// NewMockBankAccountRepository creates a new mock instance.
func NewMockBankAccountRepository(ctrl *gomock.Controller) *MockBankAccountRepository {
	mock := &MockBankAccountRepository{ctrl: ctrl}
	mock.recorder = &MockBankAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankAccountRepository) EXPECT() *MockBankAccountRepositoryMockRecorder {
	return m.recorder
}

// CreateBankAccount mocks base method.
func (m *MockBankAccountRepository) CreateBankAccount(ctx context.Context, account *model.BankAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBankAccount", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBankAccount indicates an expected call of CreateBankAccount.
func (mr *MockBankAccountRepositoryMockRecorder) CreateBankAccount(ctx, account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBankAccount", reflect.TypeOf((*MockBankAccountRepository)(nil).CreateBankAccount), ctx, account)
}

// DeleteBankAccount mocks base method.
func (m *MockBankAccountRepository) DeleteBankAccount(ctx context.Context, accountID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBankAccount", ctx, accountID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBankAccount indicates an expected call of DeleteBankAccount.
func (mr *MockBankAccountRepositoryMockRecorder) DeleteBankAccount(ctx, accountID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBankAccount", reflect.TypeOf((*MockBankAccountRepository)(nil).DeleteBankAccount), ctx, accountID, userID)
}

// GetByID mocks base method.
func (m *MockBankAccountRepository) GetByID(ctx context.Context, id, userID uuid.UUID) (*model.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, userID)
	ret0, _ := ret[0].(*model.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBankAccountRepositoryMockRecorder) GetByID(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBankAccountRepository)(nil).GetByID), ctx, id, userID)
}

// GetPrimaryBankAccount mocks base method.
func (m *MockBankAccountRepository) GetPrimaryBankAccount(ctx context.Context, userID uuid.UUID) (*model.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrimaryBankAccount", ctx, userID)
	ret0, _ := ret[0].(*model.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrimaryBankAccount indicates an expected call of GetPrimaryBankAccount.
func (mr *MockBankAccountRepositoryMockRecorder) GetPrimaryBankAccount(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrimaryBankAccount", reflect.TypeOf((*MockBankAccountRepository)(nil).GetPrimaryBankAccount), ctx, userID)
}

// GetUserBankAccounts mocks base method.
func (m *MockBankAccountRepository) GetUserBankAccounts(ctx context.Context, userID uuid.UUID) ([]*model.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBankAccounts", ctx, userID)
	ret0, _ := ret[0].([]*model.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBankAccounts indicates an expected call of GetUserBankAccounts.
func (mr *MockBankAccountRepositoryMockRecorder) GetUserBankAccounts(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBankAccounts", reflect.TypeOf((*MockBankAccountRepository)(nil).GetUserBankAccounts), ctx, userID)
}

// SetPrimaryBankAccount mocks base method.
func (m *MockBankAccountRepository) SetPrimaryBankAccount(ctx context.Context, accountID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrimaryBankAccount", ctx, accountID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPrimaryBankAccount indicates an expected call of SetPrimaryBankAccount.
func (mr *MockBankAccountRepositoryMockRecorder) SetPrimaryBankAccount(ctx, accountID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrimaryBankAccount", reflect.TypeOf((*MockBankAccountRepository)(nil).SetPrimaryBankAccount), ctx, accountID, userID)
}

// UpdateBankAccount mocks base method.
func (m *MockBankAccountRepository) UpdateBankAccount(ctx context.Context, account *model.BankAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBankAccount", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBankAccount indicates an expected call of UpdateBankAccount.
func (mr *MockBankAccountRepositoryMockRecorder) UpdateBankAccount(ctx, account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBankAccount", reflect.TypeOf((*MockBankAccountRepository)(nil).UpdateBankAccount), ctx, account)
}
