// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/refund_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "bus-booking/payment-service/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRefundRepository is a mock of RefundRepository interface.
type MockRefundRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefundRepositoryMockRecorder
}

// MockRefundRepositoryMockRecorder is the mock recorder for MockRefundRepository.
type MockRefundRepositoryMockRecorder struct {
	mock *MockRefundRepository
}

// NewMockRefundRepository creates a new mock instance.
func NewMockRefundRepository(ctrl *gomock.Controller) *MockRefundRepository {
	mock := &MockRefundRepository{ctrl: ctrl}
	mock.recorder = &MockRefundRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefundRepository) EXPECT() *MockRefundRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefundRepository) Create(ctx context.Context, refund *model.Refund) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, refund)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefundRepositoryMockRecorder) Create(ctx, refund interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefundRepository)(nil).Create), ctx, refund)
}

// GetByBookingID mocks base method.
func (m *MockRefundRepository) GetByBookingID(ctx context.Context, bookingID uuid.UUID) (*model.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBookingID", ctx, bookingID)
	ret0, _ := ret[0].(*model.Refund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBookingID indicates an expected call of GetByBookingID.
func (mr *MockRefundRepositoryMockRecorder) GetByBookingID(ctx, bookingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBookingID", reflect.TypeOf((*MockRefundRepository)(nil).GetByBookingID), ctx, bookingID)
}

// GetByID mocks base method.
func (m *MockRefundRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Refund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRefundRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRefundRepository)(nil).GetByID), ctx, id)
}

// GetCompletedRefundsTotal mocks base method.
func (m *MockRefundRepository) GetCompletedRefundsTotal(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompletedRefundsTotal", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompletedRefundsTotal indicates an expected call of GetCompletedRefundsTotal.
func (mr *MockRefundRepositoryMockRecorder) GetCompletedRefundsTotal(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompletedRefundsTotal", reflect.TypeOf((*MockRefundRepository)(nil).GetCompletedRefundsTotal), ctx)
}

// GetPendingRefundsStats mocks base method.
func (m *MockRefundRepository) GetPendingRefundsStats(ctx context.Context) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingRefundsStats", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPendingRefundsStats indicates an expected call of GetPendingRefundsStats.
func (mr *MockRefundRepositoryMockRecorder) GetPendingRefundsStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingRefundsStats", reflect.TypeOf((*MockRefundRepository)(nil).GetPendingRefundsStats), ctx)
}

// List mocks base method.
func (m *MockRefundRepository) List(ctx context.Context, query *model.RefundListQuery) ([]*model.Refund, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, query)
	ret0, _ := ret[0].([]*model.Refund)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockRefundRepositoryMockRecorder) List(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRefundRepository)(nil).List), ctx, query)
}

// ListByIDs mocks base method.
func (m *MockRefundRepository) ListByIDs(ctx context.Context, ids []uuid.UUID) ([]*model.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIDs", ctx, ids)
	ret0, _ := ret[0].([]*model.Refund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIDs indicates an expected call of ListByIDs.
func (mr *MockRefundRepositoryMockRecorder) ListByIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIDs", reflect.TypeOf((*MockRefundRepository)(nil).ListByIDs), ctx, ids)
}

// Update mocks base method.
func (m *MockRefundRepository) Update(ctx context.Context, refund *model.Refund) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, refund)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRefundRepositoryMockRecorder) Update(ctx, refund interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRefundRepository)(nil).Update), ctx, refund)
}
