run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  go: '1.23'  # Specify Go version to avoid version mismatch

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - errcheck
    - gosec
    - revive
  disable:
    - typecheck # Disabled as it can be slow

linters-settings:
  gofmt:
    simplify: true
  errcheck:
    check-blank: true
  gosec:
    excludes:
      - G104 # Audit errors not checked (too noisy)

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    # Exclude generated files
    - path: \.pb\.go$
      linters:
        - all
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
