version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - ineffassign
    - unused
    - errcheck
    - gosec
    - revive

  settings:
    errcheck:
      check-blank: true
    gosec:
      excludes:
        - G104
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck
      - path: mock_.*\.go$
        linters:
          - all
      - path: \.pb\.go$
        linters:
          - all

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
      print-linter-name: true
