export const VIETNAM_CITIES = [
  "Hà Nội",
  "TP. Hồ Chí Minh",
  "Đà Nẵng",
  "Đà Lạt",
  "Hải Phòng",
  "Cần Thơ",
  "Huế",
  "Nha Trang",
  "Quảng Ninh",
  "Bắc Ninh",
  "Bình Dương",
  "Bình Định",
  "Bình Phước",
  "Bến Tre",
  "Gia Lai",
  "Kiên Giang",
  "Lâm Đồng",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Sóc Trăng",
  "Tây Ninh",
  "Thái Nguyên",
  "Thanh Hóa",
  "Tiền Giang",
  "Trà Vinh",
  "Vĩnh Long",
  "Vũng Tàu",
];

export const POPULAR_ROUTES = [
  { id: 1, from: "Hà Nội", to: "Đà Nẵng" },
  { id: 2, from: "TP. Hồ Chí Minh", to: "Đà Lạt" },
  { id: 3, from: "Hà Nội", to: "Sa Pa" },
  { id: 4, from: "TP. Hồ Chí Minh", to: "Nha Trang" },
  { id: 5, from: "Hà Nội", to: "Hạ Long" },
];
