// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},"swagger":"2.0","info":{"description":"{{escape .Description}}","title":"{{.Title}}","contact":{"name":"API Support","email":"support@busbooking.com"},"license":{"name":"MIT","url":"https://opensource.org/licenses/MIT"},"version":"{{.Version}}"},"host":"{{.Host}}","basePath":"{{.BasePath}}","paths":{"/notifications":{"post":{"description":"Create a new notification","consumes":["application/json"],"produces":["application/json"],"tags":["notifications"],"summary":"Create a new notification","responses":{"201":{"description":"Created","schema":{"type":"object","additionalProperties":{"type":"string"}}},"400":{"description":"Invalid request","schema":{"type":"object","additionalProperties":{"type":"string"}}},"500":{"description":"Internal server error","schema":{"type":"object","additionalProperties":{"type":"string"}}}}}}},"securityDefinitions":{"BearerAuth":{"description":"Type \"Bearer\" followed by a space and JWT token.","type":"apiKey","name":"Authorization","in":"header"}}}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Payment Service API",
	Description:      "API for payment processing in the bus booking system\nThis service handles payment transactions, refunds, and payment history.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
