// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/route_stop_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "bus-booking/trip-service/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRouteStopRepository is a mock of RouteStopRepository interface.
type MockRouteStopRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRouteStopRepositoryMockRecorder
}

// MockRouteStopRepositoryMockRecorder is the mock recorder for MockRouteStopRepository.
type MockRouteStopRepositoryMockRecorder struct {
	mock *MockRouteStopRepository
}

// NewMockRouteStopRepository creates a new mock instance.
func NewMockRouteStopRepository(ctrl *gomock.Controller) *MockRouteStopRepository {
	mock := &MockRouteStopRepository{ctrl: ctrl}
	mock.recorder = &MockRouteStopRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouteStopRepository) EXPECT() *MockRouteStopRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRouteStopRepository) Create(ctx context.Context, stop *model.RouteStop) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, stop)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRouteStopRepositoryMockRecorder) Create(ctx, stop interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRouteStopRepository)(nil).Create), ctx, stop)
}

// Delete mocks base method.
func (m *MockRouteStopRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRouteStopRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRouteStopRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockRouteStopRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.RouteStop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.RouteStop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRouteStopRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRouteStopRepository)(nil).GetByID), ctx, id)
}

// ListByRouteID mocks base method.
func (m *MockRouteStopRepository) ListByRouteID(ctx context.Context, routeID uuid.UUID) ([]model.RouteStop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByRouteID", ctx, routeID)
	ret0, _ := ret[0].([]model.RouteStop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByRouteID indicates an expected call of ListByRouteID.
func (mr *MockRouteStopRepositoryMockRecorder) ListByRouteID(ctx, routeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByRouteID", reflect.TypeOf((*MockRouteStopRepository)(nil).ListByRouteID), ctx, routeID)
}

// ReorderStops mocks base method.
func (m *MockRouteStopRepository) ReorderStops(ctx context.Context, routeID uuid.UUID, stopOrders map[uuid.UUID]int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderStops", ctx, routeID, stopOrders)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReorderStops indicates an expected call of ReorderStops.
func (mr *MockRouteStopRepositoryMockRecorder) ReorderStops(ctx, routeID, stopOrders interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderStops", reflect.TypeOf((*MockRouteStopRepository)(nil).ReorderStops), ctx, routeID, stopOrders)
}

// Update mocks base method.
func (m *MockRouteStopRepository) Update(ctx context.Context, stop *model.RouteStop) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, stop)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRouteStopRepositoryMockRecorder) Update(ctx, stop interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRouteStopRepository)(nil).Update), ctx, stop)
}
