// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/bus_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	constants "bus-booking/trip-service/internal/constants"
	model "bus-booking/trip-service/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockBusRepository is a mock of BusRepository interface.
type MockBusRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBusRepositoryMockRecorder
}

// MockBusRepositoryMockRecorder is the mock recorder for MockBusRepository.
type MockBusRepositoryMockRecorder struct {
	mock *MockBusRepository
}

// NewMockBusRepository creates a new mock instance.
func NewMockBusRepository(ctrl *gomock.Controller) *MockBusRepository {
	mock := &MockBusRepository{ctrl: ctrl}
	mock.recorder = &MockBusRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBusRepository) EXPECT() *MockBusRepositoryMockRecorder {
	return m.recorder
}

// CreateBus mocks base method.
func (m *MockBusRepository) CreateBus(ctx context.Context, bus *model.Bus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBus", ctx, bus)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBus indicates an expected call of CreateBus.
func (mr *MockBusRepositoryMockRecorder) CreateBus(ctx, bus interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBus", reflect.TypeOf((*MockBusRepository)(nil).CreateBus), ctx, bus)
}

// DeleteBus mocks base method.
func (m *MockBusRepository) DeleteBus(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBus", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBus indicates an expected call of DeleteBus.
func (mr *MockBusRepositoryMockRecorder) DeleteBus(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBus", reflect.TypeOf((*MockBusRepository)(nil).DeleteBus), ctx, id)
}

// GetBusByID mocks base method.
func (m *MockBusRepository) GetBusByID(ctx context.Context, id uuid.UUID) (*model.Bus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBusByID", ctx, id)
	ret0, _ := ret[0].(*model.Bus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBusByID indicates an expected call of GetBusByID.
func (mr *MockBusRepositoryMockRecorder) GetBusByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBusByID", reflect.TypeOf((*MockBusRepository)(nil).GetBusByID), ctx, id)
}

// GetBusByPlateNumber mocks base method.
func (m *MockBusRepository) GetBusByPlateNumber(ctx context.Context, plateNumber string) (*model.Bus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBusByPlateNumber", ctx, plateNumber)
	ret0, _ := ret[0].(*model.Bus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBusByPlateNumber indicates an expected call of GetBusByPlateNumber.
func (mr *MockBusRepositoryMockRecorder) GetBusByPlateNumber(ctx, plateNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBusByPlateNumber", reflect.TypeOf((*MockBusRepository)(nil).GetBusByPlateNumber), ctx, plateNumber)
}

// GetBusWithSeatsByID mocks base method.
func (m *MockBusRepository) GetBusWithSeatsByID(ctx context.Context, id uuid.UUID) (*model.Bus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBusWithSeatsByID", ctx, id)
	ret0, _ := ret[0].(*model.Bus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBusWithSeatsByID indicates an expected call of GetBusWithSeatsByID.
func (mr *MockBusRepositoryMockRecorder) GetBusWithSeatsByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBusWithSeatsByID", reflect.TypeOf((*MockBusRepository)(nil).GetBusWithSeatsByID), ctx, id)
}

// GetByBusType mocks base method.
func (m *MockBusRepository) GetByBusType(ctx context.Context, busType constants.BusType) ([]*model.Bus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBusType", ctx, busType)
	ret0, _ := ret[0].([]*model.Bus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBusType indicates an expected call of GetByBusType.
func (mr *MockBusRepositoryMockRecorder) GetByBusType(ctx, busType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBusType", reflect.TypeOf((*MockBusRepository)(nil).GetByBusType), ctx, busType)
}

// ListBuses mocks base method.
func (m *MockBusRepository) ListBuses(ctx context.Context, page, pageSize int) ([]model.Bus, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBuses", ctx, page, pageSize)
	ret0, _ := ret[0].([]model.Bus)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBuses indicates an expected call of ListBuses.
func (mr *MockBusRepositoryMockRecorder) ListBuses(ctx, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBuses", reflect.TypeOf((*MockBusRepository)(nil).ListBuses), ctx, page, pageSize)
}

// UpdateBus mocks base method.
func (m *MockBusRepository) UpdateBus(ctx context.Context, bus *model.Bus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBus", ctx, bus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBus indicates an expected call of UpdateBus.
func (mr *MockBusRepositoryMockRecorder) UpdateBus(ctx, bus interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBus", reflect.TypeOf((*MockBusRepository)(nil).UpdateBus), ctx, bus)
}
