// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/trip_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "bus-booking/trip-service/internal/model"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTripRepository is a mock of TripRepository interface.
type MockTripRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTripRepositoryMockRecorder
}

// MockTripRepositoryMockRecorder is the mock recorder for MockTripRepository.
type MockTripRepositoryMockRecorder struct {
	mock *MockTripRepository
}

// NewMockTripRepository creates a new mock instance.
func NewMockTripRepository(ctrl *gomock.Controller) *MockTripRepository {
	mock := &MockTripRepository{ctrl: ctrl}
	mock.recorder = &MockTripRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTripRepository) EXPECT() *MockTripRepositoryMockRecorder {
	return m.recorder
}

// CreateTrip mocks base method.
func (m *MockTripRepository) CreateTrip(ctx context.Context, trip *model.Trip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTrip", ctx, trip)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTrip indicates an expected call of CreateTrip.
func (mr *MockTripRepositoryMockRecorder) CreateTrip(ctx, trip interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTrip", reflect.TypeOf((*MockTripRepository)(nil).CreateTrip), ctx, trip)
}

// DeleteTrip mocks base method.
func (m *MockTripRepository) DeleteTrip(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTrip", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTrip indicates an expected call of DeleteTrip.
func (mr *MockTripRepositoryMockRecorder) DeleteTrip(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTrip", reflect.TypeOf((*MockTripRepository)(nil).DeleteTrip), ctx, id)
}

// GetCompletedTripsForReschedule mocks base method.
func (m *MockTripRepository) GetCompletedTripsForReschedule(ctx context.Context) ([]model.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompletedTripsForReschedule", ctx)
	ret0, _ := ret[0].([]model.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompletedTripsForReschedule indicates an expected call of GetCompletedTripsForReschedule.
func (mr *MockTripRepositoryMockRecorder) GetCompletedTripsForReschedule(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompletedTripsForReschedule", reflect.TypeOf((*MockTripRepository)(nil).GetCompletedTripsForReschedule), ctx)
}

// GetTripByID mocks base method.
func (m *MockTripRepository) GetTripByID(ctx context.Context, req *model.GetTripByIDRequest, id uuid.UUID) (*model.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripByID", ctx, req, id)
	ret0, _ := ret[0].(*model.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripByID indicates an expected call of GetTripByID.
func (mr *MockTripRepositoryMockRecorder) GetTripByID(ctx, req, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripByID", reflect.TypeOf((*MockTripRepository)(nil).GetTripByID), ctx, req, id)
}

// GetTripsByBusAndDateRange mocks base method.
func (m *MockTripRepository) GetTripsByBusAndDateRange(ctx context.Context, busID uuid.UUID, startDate, endDate time.Time) ([]model.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripsByBusAndDateRange", ctx, busID, startDate, endDate)
	ret0, _ := ret[0].([]model.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripsByBusAndDateRange indicates an expected call of GetTripsByBusAndDateRange.
func (mr *MockTripRepositoryMockRecorder) GetTripsByBusAndDateRange(ctx, busID, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripsByBusAndDateRange", reflect.TypeOf((*MockTripRepository)(nil).GetTripsByBusAndDateRange), ctx, busID, startDate, endDate)
}

// GetTripsByIDs mocks base method.
func (m *MockTripRepository) GetTripsByIDs(ctx context.Context, ids []uuid.UUID) ([]model.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripsByIDs", ctx, ids)
	ret0, _ := ret[0].([]model.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripsByIDs indicates an expected call of GetTripsByIDs.
func (mr *MockTripRepositoryMockRecorder) GetTripsByIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripsByIDs", reflect.TypeOf((*MockTripRepository)(nil).GetTripsByIDs), ctx, ids)
}

// GetTripsByRouteAndDate mocks base method.
func (m *MockTripRepository) GetTripsByRouteAndDate(ctx context.Context, routeID uuid.UUID, date time.Time) ([]model.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripsByRouteAndDate", ctx, routeID, date)
	ret0, _ := ret[0].([]model.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripsByRouteAndDate indicates an expected call of GetTripsByRouteAndDate.
func (mr *MockTripRepositoryMockRecorder) GetTripsByRouteAndDate(ctx, routeID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripsByRouteAndDate", reflect.TypeOf((*MockTripRepository)(nil).GetTripsByRouteAndDate), ctx, routeID, date)
}

// ListTrips mocks base method.
func (m *MockTripRepository) ListTrips(ctx context.Context, page, pageSize int) ([]model.Trip, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTrips", ctx, page, pageSize)
	ret0, _ := ret[0].([]model.Trip)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTrips indicates an expected call of ListTrips.
func (mr *MockTripRepositoryMockRecorder) ListTrips(ctx, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTrips", reflect.TypeOf((*MockTripRepository)(nil).ListTrips), ctx, page, pageSize)
}

// SearchTrips mocks base method.
func (m *MockTripRepository) SearchTrips(ctx context.Context, req *model.TripSearchRequest) ([]model.TripDetail, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTrips", ctx, req)
	ret0, _ := ret[0].([]model.TripDetail)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchTrips indicates an expected call of SearchTrips.
func (mr *MockTripRepositoryMockRecorder) SearchTrips(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTrips", reflect.TypeOf((*MockTripRepository)(nil).SearchTrips), ctx, req)
}

// UpdateTrip mocks base method.
func (m *MockTripRepository) UpdateTrip(ctx context.Context, trip *model.Trip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrip", ctx, trip)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTrip indicates an expected call of UpdateTrip.
func (mr *MockTripRepositoryMockRecorder) UpdateTrip(ctx, trip interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrip", reflect.TypeOf((*MockTripRepository)(nil).UpdateTrip), ctx, trip)
}
