// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/route_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "bus-booking/trip-service/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRouteRepository is a mock of RouteRepository interface.
type MockRouteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRouteRepositoryMockRecorder
}

// MockRouteRepositoryMockRecorder is the mock recorder for MockRouteRepository.
type MockRouteRepositoryMockRecorder struct {
	mock *MockRouteRepository
}

// NewMockRouteRepository creates a new mock instance.
func NewMockRouteRepository(ctrl *gomock.Controller) *MockRouteRepository {
	mock := &MockRouteRepository{ctrl: ctrl}
	mock.recorder = &MockRouteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouteRepository) EXPECT() *MockRouteRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRouteRepository) Create(ctx context.Context, route *model.Route) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, route)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRouteRepositoryMockRecorder) Create(ctx, route interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRouteRepository)(nil).Create), ctx, route)
}

// Delete mocks base method.
func (m *MockRouteRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRouteRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRouteRepository)(nil).Delete), ctx, id)
}

// GetRouteByID mocks base method.
func (m *MockRouteRepository) GetRouteByID(ctx context.Context, id uuid.UUID) (*model.Route, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRouteByID", ctx, id)
	ret0, _ := ret[0].(*model.Route)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRouteByID indicates an expected call of GetRouteByID.
func (mr *MockRouteRepositoryMockRecorder) GetRouteByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRouteByID", reflect.TypeOf((*MockRouteRepository)(nil).GetRouteByID), ctx, id)
}

// GetRoutesByOriginDestination mocks base method.
func (m *MockRouteRepository) GetRoutesByOriginDestination(ctx context.Context, origin, destination string) ([]model.Route, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoutesByOriginDestination", ctx, origin, destination)
	ret0, _ := ret[0].([]model.Route)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoutesByOriginDestination indicates an expected call of GetRoutesByOriginDestination.
func (mr *MockRouteRepositoryMockRecorder) GetRoutesByOriginDestination(ctx, origin, destination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoutesByOriginDestination", reflect.TypeOf((*MockRouteRepository)(nil).GetRoutesByOriginDestination), ctx, origin, destination)
}

// GetRoutesWithRouteStops mocks base method.
func (m *MockRouteRepository) GetRoutesWithRouteStops(ctx context.Context, id uuid.UUID) (*model.Route, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoutesWithRouteStops", ctx, id)
	ret0, _ := ret[0].(*model.Route)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoutesWithRouteStops indicates an expected call of GetRoutesWithRouteStops.
func (mr *MockRouteRepositoryMockRecorder) GetRoutesWithRouteStops(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoutesWithRouteStops", reflect.TypeOf((*MockRouteRepository)(nil).GetRoutesWithRouteStops), ctx, id)
}

// ListRoutes mocks base method.
func (m *MockRouteRepository) ListRoutes(ctx context.Context, req *model.ListRoutesRequest) ([]model.Route, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoutes", ctx, req)
	ret0, _ := ret[0].([]model.Route)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRoutes indicates an expected call of ListRoutes.
func (mr *MockRouteRepositoryMockRecorder) ListRoutes(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoutes", reflect.TypeOf((*MockRouteRepository)(nil).ListRoutes), ctx, req)
}

// Update mocks base method.
func (m *MockRouteRepository) Update(ctx context.Context, route *model.Route) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, route)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRouteRepositoryMockRecorder) Update(ctx, route interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRouteRepository)(nil).Update), ctx, route)
}
