// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/seat_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "bus-booking/trip-service/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockSeatRepository is a mock of SeatRepository interface.
type MockSeatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSeatRepositoryMockRecorder
}

// MockSeatRepositoryMockRecorder is the mock recorder for MockSeatRepository.
type MockSeatRepositoryMockRecorder struct {
	mock *MockSeatRepository
}

// NewMockSeatRepository creates a new mock instance.
func NewMockSeatRepository(ctrl *gomock.Controller) *MockSeatRepository {
	mock := &MockSeatRepository{ctrl: ctrl}
	mock.recorder = &MockSeatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeatRepository) EXPECT() *MockSeatRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockSeatRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Seat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Seat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSeatRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSeatRepository)(nil).GetByID), ctx, id)
}

// GetListByBusID mocks base method.
func (m *MockSeatRepository) GetListByBusID(ctx context.Context, busID uuid.UUID) ([]model.Seat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListByBusID", ctx, busID)
	ret0, _ := ret[0].([]model.Seat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListByBusID indicates an expected call of GetListByBusID.
func (mr *MockSeatRepositoryMockRecorder) GetListByBusID(ctx, busID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListByBusID", reflect.TypeOf((*MockSeatRepository)(nil).GetListByBusID), ctx, busID)
}

// GetListByIDs mocks base method.
func (m *MockSeatRepository) GetListByIDs(ctx context.Context, ids []uuid.UUID) ([]model.Seat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListByIDs", ctx, ids)
	ret0, _ := ret[0].([]model.Seat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListByIDs indicates an expected call of GetListByIDs.
func (mr *MockSeatRepositoryMockRecorder) GetListByIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListByIDs", reflect.TypeOf((*MockSeatRepository)(nil).GetListByIDs), ctx, ids)
}

// Update mocks base method.
func (m *MockSeatRepository) Update(ctx context.Context, seat *model.Seat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, seat)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSeatRepositoryMockRecorder) Update(ctx, seat interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSeatRepository)(nil).Update), ctx, seat)
}
