// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/booking_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	booking "bus-booking/trip-service/internal/model/booking"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockBookingClient is a mock of BookingClient interface.
type MockBookingClient struct {
	ctrl     *gomock.Controller
	recorder *MockBookingClientMockRecorder
}

// MockBookingClientMockRecorder is the mock recorder for MockBookingClient.
type MockBookingClientMockRecorder struct {
	mock *MockBookingClient
}

// NewMockBookingClient creates a new mock instance.
func NewMockBookingClient(ctrl *gomock.Controller) *MockBookingClient {
	mock := &MockBookingClient{ctrl: ctrl}
	mock.recorder = &MockBookingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingClient) EXPECT() *MockBookingClientMockRecorder {
	return m.recorder
}

// GetSeatStatus mocks base method.
func (m *MockBookingClient) GetSeatStatus(ctx context.Context, tripID uuid.UUID, seatIDs []uuid.UUID) ([]booking.SeatStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeatStatus", ctx, tripID, seatIDs)
	ret0, _ := ret[0].([]booking.SeatStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeatStatus indicates an expected call of GetSeatStatus.
func (mr *MockBookingClientMockRecorder) GetSeatStatus(ctx, tripID, seatIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeatStatus", reflect.TypeOf((*MockBookingClient)(nil).GetSeatStatus), ctx, tripID, seatIDs)
}

// GetTripBookings mocks base method.
func (m *MockBookingClient) GetTripBookings(ctx context.Context, tripID uuid.UUID) ([]*booking.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripBookings", ctx, tripID)
	ret0, _ := ret[0].([]*booking.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripBookings indicates an expected call of GetTripBookings.
func (mr *MockBookingClientMockRecorder) GetTripBookings(ctx, tripID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripBookings", reflect.TypeOf((*MockBookingClient)(nil).GetTripBookings), ctx, tripID)
}

// CancelBooking mocks base method.
func (m *MockBookingClient) CancelBooking(ctx context.Context, bookingID uuid.UUID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBooking", ctx, bookingID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelBooking indicates an expected call of CancelBooking.
func (mr *MockBookingClientMockRecorder) CancelBooking(ctx, bookingID, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBooking", reflect.TypeOf((*MockBookingClient)(nil).CancelBooking), ctx, bookingID, reason)
}
