// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/payment_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	payment "bus-booking/trip-service/internal/model/payment"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPaymentClient is a mock of PaymentClient interface.
type MockPaymentClient struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentClientMockRecorder
}

// MockPaymentClientMockRecorder is the mock recorder for MockPaymentClient.
type MockPaymentClientMockRecorder struct {
	mock *MockPaymentClient
}

// NewMockPaymentClient creates a new mock instance.
func NewMockPaymentClient(ctrl *gomock.Controller) *MockPaymentClient {
	mock := &MockPaymentClient{ctrl: ctrl}
	mock.recorder = &MockPaymentClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentClient) EXPECT() *MockPaymentClientMockRecorder {
	return m.recorder
}

// CreateRefund mocks base method.
func (m *MockPaymentClient) CreateRefund(ctx context.Context, req *payment.RefundRequest) (*payment.RefundResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefund", ctx, req)
	ret0, _ := ret[0].(*payment.RefundResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRefund indicates an expected call of CreateRefund.
func (mr *MockPaymentClientMockRecorder) CreateRefund(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefund", reflect.TypeOf((*MockPaymentClient)(nil).CreateRefund), ctx, req)
}
