// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/booking_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "bus-booking/booking-service/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockBookingRepository is a mock of BookingRepository interface.
type MockBookingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepositoryMockRecorder
}

// MockBookingRepositoryMockRecorder is the mock recorder for MockBookingRepository.
type MockBookingRepositoryMockRecorder struct {
	mock *MockBookingRepository
}

// NewMockBookingRepository creates a new mock instance.
func NewMockBookingRepository(ctrl *gomock.Controller) *MockBookingRepository {
	mock := &MockBookingRepository{ctrl: ctrl}
	mock.recorder = &MockBookingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepository) EXPECT() *MockBookingRepositoryMockRecorder {
	return m.recorder
}

// CancelBooking mocks base method.
func (m *MockBookingRepository) CancelBooking(ctx context.Context, id uuid.UUID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBooking", ctx, id, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelBooking indicates an expected call of CancelBooking.
func (mr *MockBookingRepositoryMockRecorder) CancelBooking(ctx, id, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBooking", reflect.TypeOf((*MockBookingRepository)(nil).CancelBooking), ctx, id, reason)
}

// CreateBooking mocks base method.
func (m *MockBookingRepository) CreateBooking(ctx context.Context, booking *model.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", ctx, booking)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockBookingRepositoryMockRecorder) CreateBooking(ctx, booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockBookingRepository)(nil).CreateBooking), ctx, booking)
}

// GetBookedSeatIDs mocks base method.
func (m *MockBookingRepository) GetBookedSeatIDs(ctx context.Context, tripID uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookedSeatIDs", ctx, tripID)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookedSeatIDs indicates an expected call of GetBookedSeatIDs.
func (mr *MockBookingRepositoryMockRecorder) GetBookedSeatIDs(ctx, tripID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookedSeatIDs", reflect.TypeOf((*MockBookingRepository)(nil).GetBookedSeatIDs), ctx, tripID)
}

// GetBookingByID mocks base method.
func (m *MockBookingRepository) GetBookingByID(ctx context.Context, id uuid.UUID) (*model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingByID", ctx, id)
	ret0, _ := ret[0].(*model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingByID indicates an expected call of GetBookingByID.
func (mr *MockBookingRepositoryMockRecorder) GetBookingByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingByID", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingByID), ctx, id)
}

// GetBookingByReference mocks base method.
func (m *MockBookingRepository) GetBookingByReference(ctx context.Context, reference string) (*model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingByReference", ctx, reference)
	ret0, _ := ret[0].(*model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingByReference indicates an expected call of GetBookingByReference.
func (mr *MockBookingRepositoryMockRecorder) GetBookingByReference(ctx, reference interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingByReference", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingByReference), ctx, reference)
}

// GetBookingsByTripID mocks base method.
func (m *MockBookingRepository) GetBookingsByTripID(ctx context.Context, tripID uuid.UUID, limit, offset int) ([]*model.Booking, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingsByTripID", ctx, tripID, limit, offset)
	ret0, _ := ret[0].([]*model.Booking)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBookingsByTripID indicates an expected call of GetBookingsByTripID.
func (mr *MockBookingRepositoryMockRecorder) GetBookingsByTripID(ctx, tripID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingsByTripID", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingsByTripID), ctx, tripID, limit, offset)
}

// GetBookingsByUserID mocks base method.
func (m *MockBookingRepository) GetBookingsByUserID(ctx context.Context, userID uuid.UUID, statuses []model.BookingStatus, limit, offset int) ([]*model.Booking, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingsByUserID", ctx, userID, statuses, limit, offset)
	ret0, _ := ret[0].([]*model.Booking)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBookingsByUserID indicates an expected call of GetBookingsByUserID.
func (mr *MockBookingRepositoryMockRecorder) GetBookingsByUserID(ctx, userID, statuses, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingsByUserID", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingsByUserID), ctx, userID, statuses, limit, offset)
}

// GetTripBookings mocks base method.
func (m *MockBookingRepository) GetTripBookings(ctx context.Context, tripID uuid.UUID, page, limit int) ([]*model.Booking, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripBookings", ctx, tripID, page, limit)
	ret0, _ := ret[0].([]*model.Booking)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTripBookings indicates an expected call of GetTripBookings.
func (mr *MockBookingRepositoryMockRecorder) GetTripBookings(ctx, tripID, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripBookings", reflect.TypeOf((*MockBookingRepository)(nil).GetTripBookings), ctx, tripID, page, limit)
}

// ListBookings mocks base method.
func (m *MockBookingRepository) ListBookings(ctx context.Context, req model.ListBookingsRequest) ([]*model.Booking, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookings", ctx, req)
	ret0, _ := ret[0].([]*model.Booking)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBookings indicates an expected call of ListBookings.
func (mr *MockBookingRepositoryMockRecorder) ListBookings(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookings", reflect.TypeOf((*MockBookingRepository)(nil).ListBookings), ctx, req)
}

// UpdateBooking mocks base method.
func (m *MockBookingRepository) UpdateBooking(ctx context.Context, booking *model.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBooking", ctx, booking)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBooking indicates an expected call of UpdateBooking.
func (mr *MockBookingRepositoryMockRecorder) UpdateBooking(ctx, booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBooking", reflect.TypeOf((*MockBookingRepository)(nil).UpdateBooking), ctx, booking)
}

// UpdateStatus mocks base method.
func (m *MockBookingRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status model.BookingStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockBookingRepositoryMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockBookingRepository)(nil).UpdateStatus), ctx, id, status)
}
