// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/booking_stats_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "bus-booking/booking-service/internal/model"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockBookingStatsRepository is a mock of BookingStatsRepository interface.
type MockBookingStatsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookingStatsRepositoryMockRecorder
}

// MockBookingStatsRepositoryMockRecorder is the mock recorder for MockBookingStatsRepository.
type MockBookingStatsRepositoryMockRecorder struct {
	mock *MockBookingStatsRepository
}

// NewMockBookingStatsRepository creates a new mock instance.
func NewMockBookingStatsRepository(ctrl *gomock.Controller) *MockBookingStatsRepository {
	mock := &MockBookingStatsRepository{ctrl: ctrl}
	mock.recorder = &MockBookingStatsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingStatsRepository) EXPECT() *MockBookingStatsRepositoryMockRecorder {
	return m.recorder
}

// GetBookingStatsByDateRange mocks base method.
func (m *MockBookingStatsRepository) GetBookingStatsByDateRange(ctx context.Context, startDate, endDate time.Time) (*model.BookingStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingStatsByDateRange", ctx, startDate, endDate)
	ret0, _ := ret[0].(*model.BookingStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingStatsByDateRange indicates an expected call of GetBookingStatsByDateRange.
func (mr *MockBookingStatsRepositoryMockRecorder) GetBookingStatsByDateRange(ctx, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingStatsByDateRange", reflect.TypeOf((*MockBookingStatsRepository)(nil).GetBookingStatsByDateRange), ctx, startDate, endDate)
}

// GetPopularTrips mocks base method.
func (m *MockBookingStatsRepository) GetPopularTrips(ctx context.Context, limit, days int) ([]*model.TripBookingStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopularTrips", ctx, limit, days)
	ret0, _ := ret[0].([]*model.TripBookingStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopularTrips indicates an expected call of GetPopularTrips.
func (mr *MockBookingStatsRepositoryMockRecorder) GetPopularTrips(ctx, limit, days interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopularTrips", reflect.TypeOf((*MockBookingStatsRepository)(nil).GetPopularTrips), ctx, limit, days)
}
