// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/seat_lock_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockSeatLockRepository is a mock of SeatLockRepository interface.
type MockSeatLockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSeatLockRepositoryMockRecorder
}

// MockSeatLockRepositoryMockRecorder is the mock recorder for MockSeatLockRepository.
type MockSeatLockRepositoryMockRecorder struct {
	mock *MockSeatLockRepository
}

// NewMockSeatLockRepository creates a new mock instance.
func NewMockSeatLockRepository(ctrl *gomock.Controller) *MockSeatLockRepository {
	mock := &MockSeatLockRepository{ctrl: ctrl}
	mock.recorder = &MockSeatLockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeatLockRepository) EXPECT() *MockSeatLockRepositoryMockRecorder {
	return m.recorder
}

// CleanExpiredLocks mocks base method.
func (m *MockSeatLockRepository) CleanExpiredLocks(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanExpiredLocks", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanExpiredLocks indicates an expected call of CleanExpiredLocks.
func (mr *MockSeatLockRepositoryMockRecorder) CleanExpiredLocks(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanExpiredLocks", reflect.TypeOf((*MockSeatLockRepository)(nil).CleanExpiredLocks), ctx)
}

// GetLockedSeats mocks base method.
func (m *MockSeatLockRepository) GetLockedSeats(ctx context.Context, tripID uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLockedSeats", ctx, tripID)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLockedSeats indicates an expected call of GetLockedSeats.
func (mr *MockSeatLockRepositoryMockRecorder) GetLockedSeats(ctx, tripID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLockedSeats", reflect.TypeOf((*MockSeatLockRepository)(nil).GetLockedSeats), ctx, tripID)
}

// IsLocked mocks base method.
func (m *MockSeatLockRepository) IsLocked(ctx context.Context, tripID, seatID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLocked", ctx, tripID, seatID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLocked indicates an expected call of IsLocked.
func (mr *MockSeatLockRepositoryMockRecorder) IsLocked(ctx, tripID, seatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLocked", reflect.TypeOf((*MockSeatLockRepository)(nil).IsLocked), ctx, tripID, seatID)
}

// LockSeats mocks base method.
func (m *MockSeatLockRepository) LockSeats(ctx context.Context, tripID uuid.UUID, seatIDs []uuid.UUID, sessionID string, duration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockSeats", ctx, tripID, seatIDs, sessionID, duration)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockSeats indicates an expected call of LockSeats.
func (mr *MockSeatLockRepositoryMockRecorder) LockSeats(ctx, tripID, seatIDs, sessionID, duration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockSeats", reflect.TypeOf((*MockSeatLockRepository)(nil).LockSeats), ctx, tripID, seatIDs, sessionID, duration)
}

// UnlockSeats mocks base method.
func (m *MockSeatLockRepository) UnlockSeats(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockSeats", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockSeats indicates an expected call of UnlockSeats.
func (mr *MockSeatLockRepositoryMockRecorder) UnlockSeats(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockSeats", reflect.TypeOf((*MockSeatLockRepository)(nil).UnlockSeats), ctx, sessionID)
}

// UnlockSpecificSeats mocks base method.
func (m *MockSeatLockRepository) UnlockSpecificSeats(ctx context.Context, tripID uuid.UUID, seatIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockSpecificSeats", ctx, tripID, seatIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockSpecificSeats indicates an expected call of UnlockSpecificSeats.
func (mr *MockSeatLockRepositoryMockRecorder) UnlockSpecificSeats(ctx, tripID, seatIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockSpecificSeats", reflect.TypeOf((*MockSeatLockRepository)(nil).UnlockSpecificSeats), ctx, tripID, seatIDs)
}
