// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/review_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "bus-booking/booking-service/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockReviewRepository is a mock of ReviewRepository interface.
type MockReviewRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReviewRepositoryMockRecorder
}

// MockReviewRepositoryMockRecorder is the mock recorder for MockReviewRepository.
type MockReviewRepositoryMockRecorder struct {
	mock *MockReviewRepository
}

// NewMockReviewRepository creates a new mock instance.
func NewMockReviewRepository(ctrl *gomock.Controller) *MockReviewRepository {
	mock := &MockReviewRepository{ctrl: ctrl}
	mock.recorder = &MockReviewRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewRepository) EXPECT() *MockReviewRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReviewRepository) Create(ctx context.Context, review *model.Review) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, review)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReviewRepositoryMockRecorder) Create(ctx, review interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReviewRepository)(nil).Create), ctx, review)
}

// Delete mocks base method.
func (m *MockReviewRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockReviewRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReviewRepository)(nil).Delete), ctx, id)
}

// GetByBookingID mocks base method.
func (m *MockReviewRepository) GetByBookingID(ctx context.Context, bookingID uuid.UUID) (*model.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBookingID", ctx, bookingID)
	ret0, _ := ret[0].(*model.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBookingID indicates an expected call of GetByBookingID.
func (mr *MockReviewRepositoryMockRecorder) GetByBookingID(ctx, bookingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBookingID", reflect.TypeOf((*MockReviewRepository)(nil).GetByBookingID), ctx, bookingID)
}

// GetByID mocks base method.
func (m *MockReviewRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReviewRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReviewRepository)(nil).GetByID), ctx, id)
}

// GetTripReviewSummary mocks base method.
func (m *MockReviewRepository) GetTripReviewSummary(ctx context.Context, tripID uuid.UUID) (*model.TripReviewSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripReviewSummary", ctx, tripID)
	ret0, _ := ret[0].(*model.TripReviewSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripReviewSummary indicates an expected call of GetTripReviewSummary.
func (mr *MockReviewRepositoryMockRecorder) GetTripReviewSummary(ctx, tripID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripReviewSummary", reflect.TypeOf((*MockReviewRepository)(nil).GetTripReviewSummary), ctx, tripID)
}

// GetTripReviews mocks base method.
func (m *MockReviewRepository) GetTripReviews(ctx context.Context, req *model.GetTripReviewsRequest) ([]*model.Review, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripReviews", ctx, req)
	ret0, _ := ret[0].([]*model.Review)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTripReviews indicates an expected call of GetTripReviews.
func (mr *MockReviewRepositoryMockRecorder) GetTripReviews(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripReviews", reflect.TypeOf((*MockReviewRepository)(nil).GetTripReviews), ctx, req)
}

// GetUserReviews mocks base method.
func (m *MockReviewRepository) GetUserReviews(ctx context.Context, userID uuid.UUID, page, pageSize int) ([]*model.Review, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserReviews", ctx, userID, page, pageSize)
	ret0, _ := ret[0].([]*model.Review)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserReviews indicates an expected call of GetUserReviews.
func (mr *MockReviewRepositoryMockRecorder) GetUserReviews(ctx, userID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReviews", reflect.TypeOf((*MockReviewRepository)(nil).GetUserReviews), ctx, userID, page, pageSize)
}

// Update mocks base method.
func (m *MockReviewRepository) Update(ctx context.Context, id uuid.UUID, updates map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockReviewRepositoryMockRecorder) Update(ctx, id, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockReviewRepository)(nil).Update), ctx, id, updates)
}
