// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/seat_status_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "bus-booking/booking-service/internal/model"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockSeatStatusRepository is a mock of SeatStatusRepository interface.
type MockSeatStatusRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSeatStatusRepositoryMockRecorder
}

// MockSeatStatusRepositoryMockRecorder is the mock recorder for MockSeatStatusRepository.
type MockSeatStatusRepositoryMockRecorder struct {
	mock *MockSeatStatusRepository
}

// NewMockSeatStatusRepository creates a new mock instance.
func NewMockSeatStatusRepository(ctrl *gomock.Controller) *MockSeatStatusRepository {
	mock := &MockSeatStatusRepository{ctrl: ctrl}
	mock.recorder = &MockSeatStatusRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeatStatusRepository) EXPECT() *MockSeatStatusRepositoryMockRecorder {
	return m.recorder
}

// BulkUpdateSeatStatus mocks base method.
func (m *MockSeatStatusRepository) BulkUpdateSeatStatus(ctx context.Context, seatStatuses []*model.SeatStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateSeatStatus", ctx, seatStatuses)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateSeatStatus indicates an expected call of BulkUpdateSeatStatus.
func (mr *MockSeatStatusRepositoryMockRecorder) BulkUpdateSeatStatus(ctx, seatStatuses interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateSeatStatus", reflect.TypeOf((*MockSeatStatusRepository)(nil).BulkUpdateSeatStatus), ctx, seatStatuses)
}

// GetAvailableSeats mocks base method.
func (m *MockSeatStatusRepository) GetAvailableSeats(ctx context.Context, tripID uuid.UUID) ([]*model.SeatStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableSeats", ctx, tripID)
	ret0, _ := ret[0].([]*model.SeatStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableSeats indicates an expected call of GetAvailableSeats.
func (mr *MockSeatStatusRepositoryMockRecorder) GetAvailableSeats(ctx, tripID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableSeats", reflect.TypeOf((*MockSeatStatusRepository)(nil).GetAvailableSeats), ctx, tripID)
}

// GetSeatStatusByTripID mocks base method.
func (m *MockSeatStatusRepository) GetSeatStatusByTripID(ctx context.Context, tripID uuid.UUID) ([]*model.SeatStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeatStatusByTripID", ctx, tripID)
	ret0, _ := ret[0].([]*model.SeatStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeatStatusByTripID indicates an expected call of GetSeatStatusByTripID.
func (mr *MockSeatStatusRepositoryMockRecorder) GetSeatStatusByTripID(ctx, tripID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeatStatusByTripID", reflect.TypeOf((*MockSeatStatusRepository)(nil).GetSeatStatusByTripID), ctx, tripID)
}

// ReleaseSeat mocks base method.
func (m *MockSeatStatusRepository) ReleaseSeat(ctx context.Context, tripID, seatID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseSeat", ctx, tripID, seatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseSeat indicates an expected call of ReleaseSeat.
func (mr *MockSeatStatusRepositoryMockRecorder) ReleaseSeat(ctx, tripID, seatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseSeat", reflect.TypeOf((*MockSeatStatusRepository)(nil).ReleaseSeat), ctx, tripID, seatID)
}

// ReserveSeat mocks base method.
func (m *MockSeatStatusRepository) ReserveSeat(ctx context.Context, tripID, seatID, userID uuid.UUID, reservationTime time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveSeat", ctx, tripID, seatID, userID, reservationTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReserveSeat indicates an expected call of ReserveSeat.
func (mr *MockSeatStatusRepositoryMockRecorder) ReserveSeat(ctx, tripID, seatID, userID, reservationTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveSeat", reflect.TypeOf((*MockSeatStatusRepository)(nil).ReserveSeat), ctx, tripID, seatID, userID, reservationTime)
}

// UpdateSeatStatus mocks base method.
func (m *MockSeatStatusRepository) UpdateSeatStatus(ctx context.Context, seatStatus *model.SeatStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSeatStatus", ctx, seatStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSeatStatus indicates an expected call of UpdateSeatStatus.
func (mr *MockSeatStatusRepositoryMockRecorder) UpdateSeatStatus(ctx, seatStatus interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSeatStatus", reflect.TypeOf((*MockSeatStatusRepository)(nil).UpdateSeatStatus), ctx, seatStatus)
}
