// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/notification_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	client "bus-booking/booking-service/internal/client"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNotificationClient is a mock of NotificationClient interface.
type MockNotificationClient struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationClientMockRecorder
}

// MockNotificationClientMockRecorder is the mock recorder for MockNotificationClient.
type MockNotificationClientMockRecorder struct {
	mock *MockNotificationClient
}

// NewMockNotificationClient creates a new mock instance.
func NewMockNotificationClient(ctrl *gomock.Controller) *MockNotificationClient {
	mock := &MockNotificationClient{ctrl: ctrl}
	mock.recorder = &MockNotificationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationClient) EXPECT() *MockNotificationClientMockRecorder {
	return m.recorder
}

// SendBookingConfirmation mocks base method.
func (m *MockNotificationClient) SendBookingConfirmation(ctx context.Context, req *client.BookingConfirmationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBookingConfirmation", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendBookingConfirmation indicates an expected call of SendBookingConfirmation.
func (mr *MockNotificationClientMockRecorder) SendBookingConfirmation(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBookingConfirmation", reflect.TypeOf((*MockNotificationClient)(nil).SendBookingConfirmation), ctx, req)
}

// SendBookingFailure mocks base method.
func (m *MockNotificationClient) SendBookingFailure(ctx context.Context, req *client.BookingFailureRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBookingFailure", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendBookingFailure indicates an expected call of SendBookingFailure.
func (mr *MockNotificationClientMockRecorder) SendBookingFailure(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBookingFailure", reflect.TypeOf((*MockNotificationClient)(nil).SendBookingFailure), ctx, req)
}

// SendBookingPending mocks base method.
func (m *MockNotificationClient) SendBookingPending(ctx context.Context, req *client.BookingPendingRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBookingPending", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendBookingPending indicates an expected call of SendBookingPending.
func (mr *MockNotificationClientMockRecorder) SendBookingPending(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBookingPending", reflect.TypeOf((*MockNotificationClient)(nil).SendBookingPending), ctx, req)
}

// SendTripReminder mocks base method.
func (m *MockNotificationClient) SendTripReminder(ctx context.Context, req *client.TripReminderRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTripReminder", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTripReminder indicates an expected call of SendTripReminder.
func (mr *MockNotificationClientMockRecorder) SendTripReminder(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTripReminder", reflect.TypeOf((*MockNotificationClient)(nil).SendTripReminder), ctx, req)
}
