// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/payment_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	payment "bus-booking/booking-service/internal/model/payment"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockPaymentClient is a mock of PaymentClient interface.
type MockPaymentClient struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentClientMockRecorder
}

// MockPaymentClientMockRecorder is the mock recorder for MockPaymentClient.
type MockPaymentClientMockRecorder struct {
	mock *MockPaymentClient
}

// NewMockPaymentClient creates a new mock instance.
func NewMockPaymentClient(ctrl *gomock.Controller) *MockPaymentClient {
	mock := &MockPaymentClient{ctrl: ctrl}
	mock.recorder = &MockPaymentClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentClient) EXPECT() *MockPaymentClientMockRecorder {
	return m.recorder
}

// CancelTransaction mocks base method.
func (m *MockPaymentClient) CancelTransaction(ctx context.Context, transactionID uuid.UUID) (*payment.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelTransaction", ctx, transactionID)
	ret0, _ := ret[0].(*payment.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelTransaction indicates an expected call of CancelTransaction.
func (mr *MockPaymentClientMockRecorder) CancelTransaction(ctx, transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelTransaction", reflect.TypeOf((*MockPaymentClient)(nil).CancelTransaction), ctx, transactionID)
}

// CreateTransaction mocks base method.
func (m *MockPaymentClient) CreateTransaction(ctx context.Context, req *payment.CreateTransactionRequest) (*payment.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, req)
	ret0, _ := ret[0].(*payment.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockPaymentClientMockRecorder) CreateTransaction(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockPaymentClient)(nil).CreateTransaction), ctx, req)
}

// GetTransactionByID mocks base method.
func (m *MockPaymentClient) GetTransactionByID(ctx context.Context, id uuid.UUID) (*payment.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByID", ctx, id)
	ret0, _ := ret[0].(*payment.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByID indicates an expected call of GetTransactionByID.
func (mr *MockPaymentClientMockRecorder) GetTransactionByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByID", reflect.TypeOf((*MockPaymentClient)(nil).GetTransactionByID), ctx, id)
}
