// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/trip_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	trip "bus-booking/booking-service/internal/model/trip"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTripClient is a mock of TripClient interface.
type MockTripClient struct {
	ctrl     *gomock.Controller
	recorder *MockTripClientMockRecorder
}

// MockTripClientMockRecorder is the mock recorder for MockTripClient.
type MockTripClientMockRecorder struct {
	mock *MockTripClient
}

// NewMockTripClient creates a new mock instance.
func NewMockTripClient(ctrl *gomock.Controller) *MockTripClient {
	mock := &MockTripClient{ctrl: ctrl}
	mock.recorder = &MockTripClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTripClient) EXPECT() *MockTripClientMockRecorder {
	return m.recorder
}

// GetTripByID mocks base method.
func (m *MockTripClient) GetTripByID(ctx context.Context, req trip.GetTripByIDRequest, ripID uuid.UUID) (*trip.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripByID", ctx, req, ripID)
	ret0, _ := ret[0].(*trip.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripByID indicates an expected call of GetTripByID.
func (mr *MockTripClientMockRecorder) GetTripByID(ctx, req, ripID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripByID", reflect.TypeOf((*MockTripClient)(nil).GetTripByID), ctx, req, ripID)
}

// GetTripsByIDs mocks base method.
func (m *MockTripClient) GetTripsByIDs(ctx context.Context, req trip.GetTripByIDRequest, tripIDs []uuid.UUID) ([]trip.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripsByIDs", ctx, req, tripIDs)
	ret0, _ := ret[0].([]trip.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripsByIDs indicates an expected call of GetTripsByIDs.
func (mr *MockTripClientMockRecorder) GetTripsByIDs(ctx, req, tripIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripsByIDs", reflect.TypeOf((*MockTripClient)(nil).GetTripsByIDs), ctx, req, tripIDs)
}

// ListSeatsByIDs mocks base method.
func (m *MockTripClient) ListSeatsByIDs(ctx context.Context, seatIDs []uuid.UUID) ([]trip.Seat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSeatsByIDs", ctx, seatIDs)
	ret0, _ := ret[0].([]trip.Seat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSeatsByIDs indicates an expected call of ListSeatsByIDs.
func (mr *MockTripClientMockRecorder) ListSeatsByIDs(ctx, seatIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSeatsByIDs", reflect.TypeOf((*MockTripClient)(nil).ListSeatsByIDs), ctx, seatIDs)
}
