// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/booking_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	booking "bus-booking/payment-service/internal/model/booking"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockBookingClient is a mock of BookingClient interface.
type MockBookingClient struct {
	ctrl     *gomock.Controller
	recorder *MockBookingClientMockRecorder
}

// MockBookingClientMockRecorder is the mock recorder for MockBookingClient.
type MockBookingClientMockRecorder struct {
	mock *MockBookingClient
}

// NewMockBookingClient creates a new mock instance.
func NewMockBookingClient(ctrl *gomock.Controller) *MockBookingClient {
	mock := &MockBookingClient{ctrl: ctrl}
	mock.recorder = &MockBookingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingClient) EXPECT() *MockBookingClientMockRecorder {
	return m.recorder
}

// UpdateBookingStatus mocks base method.
func (m *MockBookingClient) UpdateBookingStatus(ctx context.Context, req *booking.UpdateBookingStatusRequest, bookingID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBookingStatus", ctx, req, bookingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBookingStatus indicates an expected call of UpdateBookingStatus.
func (mr *MockBookingClientMockRecorder) UpdateBookingStatus(ctx, req, bookingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookingStatus", reflect.TypeOf((*MockBookingClient)(nil).UpdateBookingStatus), ctx, req, bookingID)
}
