// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/constants_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "bus-booking/payment-service/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConstantsService is a mock of ConstantsService interface.
type MockConstantsService struct {
	ctrl     *gomock.Controller
	recorder *MockConstantsServiceMockRecorder
}

// MockConstantsServiceMockRecorder is the mock recorder for MockConstantsService.
type MockConstantsServiceMockRecorder struct {
	mock *MockConstantsService
}

// NewMockConstantsService creates a new mock instance.
func NewMockConstantsService(ctrl *gomock.Controller) *MockConstantsService {
	mock := &MockConstantsService{ctrl: ctrl}
	mock.recorder = &MockConstantsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConstantsService) EXPECT() *MockConstantsServiceMockRecorder {
	return m.recorder
}

// GetBanks mocks base method.
func (m *MockConstantsService) GetBanks(ctx context.Context) ([]model.BankConstant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBanks", ctx)
	ret0, _ := ret[0].([]model.BankConstant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBanks indicates an expected call of GetBanks.
func (mr *MockConstantsServiceMockRecorder) GetBanks(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBanks", reflect.TypeOf((*MockConstantsService)(nil).GetBanks), ctx)
}
