// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/excel_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "bus-booking/payment-service/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockExcelService is a mock of ExcelService interface.
type MockExcelService struct {
	ctrl     *gomock.Controller
	recorder *MockExcelServiceMockRecorder
}

// MockExcelServiceMockRecorder is the mock recorder for MockExcelService.
type MockExcelServiceMockRecorder struct {
	mock *MockExcelService
}

// NewMockExcelService creates a new mock instance.
func NewMockExcelService(ctrl *gomock.Controller) *MockExcelService {
	mock := &MockExcelService{ctrl: ctrl}
	mock.recorder = &MockExcelServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExcelService) EXPECT() *MockExcelServiceMockRecorder {
	return m.recorder
}

// GenerateRefundExcel mocks base method.
func (m *MockExcelService) GenerateRefundExcel(refunds []*model.RefundExportItem) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefundExcel", refunds)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRefundExcel indicates an expected call of GenerateRefundExcel.
func (mr *MockExcelServiceMockRecorder) GenerateRefundExcel(refunds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefundExcel", reflect.TypeOf((*MockExcelService)(nil).GenerateRefundExcel), refunds)
}
