// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/payos_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "bus-booking/payment-service/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	payos "github.com/payOSHQ/payos-lib-golang/v2"
)

// MockPayOSService is a mock of PayOSService interface.
type MockPayOSService struct {
	ctrl     *gomock.Controller
	recorder *MockPayOSServiceMockRecorder
}

// MockPayOSServiceMockRecorder is the mock recorder for MockPayOSService.
type MockPayOSServiceMockRecorder struct {
	mock *MockPayOSService
}

// NewMockPayOSService creates a new mock instance.
func NewMockPayOSService(ctrl *gomock.Controller) *MockPayOSService {
	mock := &MockPayOSService{ctrl: ctrl}
	mock.recorder = &MockPayOSServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayOSService) EXPECT() *MockPayOSServiceMockRecorder {
	return m.recorder
}

// CancelPaymentLink mocks base method.
func (m *MockPayOSService) CancelPaymentLink(ctx context.Context, paymentLinkID string, cancellationReason *string) (*payos.PaymentLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelPaymentLink", ctx, paymentLinkID, cancellationReason)
	ret0, _ := ret[0].(*payos.PaymentLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelPaymentLink indicates an expected call of CancelPaymentLink.
func (mr *MockPayOSServiceMockRecorder) CancelPaymentLink(ctx, paymentLinkID, cancellationReason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelPaymentLink", reflect.TypeOf((*MockPayOSService)(nil).CancelPaymentLink), ctx, paymentLinkID, cancellationReason)
}

// CreatePaymentLink mocks base method.
func (m *MockPayOSService) CreatePaymentLink(ctx context.Context, req *model.CreatePaymentLinkRequest) (*payos.CreatePaymentLinkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaymentLink", ctx, req)
	ret0, _ := ret[0].(*payos.CreatePaymentLinkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePaymentLink indicates an expected call of CreatePaymentLink.
func (mr *MockPayOSServiceMockRecorder) CreatePaymentLink(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentLink", reflect.TypeOf((*MockPayOSService)(nil).CreatePaymentLink), ctx, req)
}

// GetPaymentLink mocks base method.
func (m *MockPayOSService) GetPaymentLink(ctx context.Context, paymentLinkID string) (*payos.PaymentLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentLink", ctx, paymentLinkID)
	ret0, _ := ret[0].(*payos.PaymentLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentLink indicates an expected call of GetPaymentLink.
func (mr *MockPayOSServiceMockRecorder) GetPaymentLink(ctx, paymentLinkID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentLink", reflect.TypeOf((*MockPayOSService)(nil).GetPaymentLink), ctx, paymentLinkID)
}

// ToTransactionStatus mocks base method.
func (m *MockPayOSService) ToTransactionStatus(payOSStatus payos.PaymentLinkStatus) model.TransactionStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToTransactionStatus", payOSStatus)
	ret0, _ := ret[0].(model.TransactionStatus)
	return ret0
}

// ToTransactionStatus indicates an expected call of ToTransactionStatus.
func (mr *MockPayOSServiceMockRecorder) ToTransactionStatus(payOSStatus interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToTransactionStatus", reflect.TypeOf((*MockPayOSService)(nil).ToTransactionStatus), payOSStatus)
}

// VerifyWebhook mocks base method.
func (m *MockPayOSService) VerifyWebhook(ctx context.Context, webhookData map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyWebhook", ctx, webhookData)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyWebhook indicates an expected call of VerifyWebhook.
func (mr *MockPayOSServiceMockRecorder) VerifyWebhook(ctx, webhookData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyWebhook", reflect.TypeOf((*MockPayOSService)(nil).VerifyWebhook), ctx, webhookData)
}
